//@@viewOn:imports
import UU5 from "uu5g04";
import { createVisualComponent, useState, useEffect } from "uu5g04-hooks";
import Config from "./config/config";
//@@viewOff:imports

const STATICS = {
  //@@viewOn:statics
  displayName: Config.TAG + "ViewRecipe",
  nestingLevel: "bigBoxCollection",
  //@@viewOff:statics
};

export const ViewRecipe = createVisualComponent({
  ...STATICS,

  //@@viewOn:propTypes
  propTypes: {},
  //@@viewOff:propTypes

  //@@viewOn:defaultProps
  defaultProps: {},
  //@@viewOff:defaultProps

  render(props) {
    props.recipe = {
      recipeID: 0,//unique autogenerated numeric ID
      recipeName:  "test",//name of the recipe
      numberOfPortions: 5,//default number of portions created
      timeForPreparation: 20,//time for preparation in minutes
      category: 1,//category (as a number) of the drink selected from predefined (0 = Alcoholic, 1 = NonAlcoholic, 2 = Coffe)
      listOfIngredients: [
        {
          ingredientName: "rum",//ID of the ingredient
          ingredientAmount: 100, //amount of the ingredient in ml, g, pieces, etc.
          ingredientMeasure: 'cl',
        }
      ],
      steps: [
        "vodka", "tomato"
      ]//steps of the preparation
    };

    const [listOfIngredients, setListOfIngridients] = useState(props.recipe.listOfIngredients.map(ingredient => Object.assign({}, ingredient, { initialAmount: ingredient.ingredientAmount })))
    const [numberOfPortions, setNumberOfPortions] = useState(props.recipe.numberOfPortions)

    //@@viewOn:private
    //@@viewOff:private

    //@@viewOn:interface
    //@@viewOff:interface

    //@@viewOn:render
    const className = Config.Css.css``;
    const attrs = UU5.Common.VisualComponent.getAttrs(props, className);
    const currentNestingLevel = UU5.Utils.NestingLevel.getNestingLevel(props, STATICS);

    return currentNestingLevel ? (
      <div {...attrs}>
        <UU5.Bricks.Label content="Ingredients for" />
        <UU5.Forms.Number value={numberOfPortions} min={1} rounded={true} decimals={0} decimalsViewRounded="round" onChange={(component) => {
          const initialValue = props.recipe.numberOfPortions;
          const value = +component.value;

          setListOfIngridients(listOfIngredients.map(ingredient => Object.assign({}, ingredient, { ingredientAmount: ingredient.initialAmount / initialValue * value })))
          setNumberOfPortions(value)

        }} />
        <UU5.Bricks.Span style={{ color: "red", fontSize: "30px" }}>{props.recipe.recipeName}</UU5.Bricks.Span>
        <UU5.Bricks.Table>
          <UU5.Bricks.Table.TBody>
            {listOfIngredients.map(ingredient => (
              <UU5.Bricks.Table.Tr>
                <UU5.Bricks.Table.Td content={ingredient.ingredientName} />
                <UU5.Bricks.Table.Td content={`${ingredient.ingredientAmount} ${ingredient.ingredientMeasure}`} />
              </UU5.Bricks.Table.Tr>
            ))}
          </UU5.Bricks.Table.TBody>
        </UU5.Bricks.Table>
        <UU5.Bricks.Span style={{ color: "black", fontSize: "30px" }}>Preparation</UU5.Bricks.Span>
        <UU5.Bricks.Table>
          <UU5.Bricks.Table.TBody>
            {props.recipe.steps.map((step, index) => (
              <UU5.Bricks.Table.Tr>
                <UU5.Bricks.Table.Td content={`${index + 1}. ${step}`} />
              </UU5.Bricks.Table.Tr>
            ))}
          </UU5.Bricks.Table.TBody>
        </UU5.Bricks.Table>
      </div>
    ) : null;
    //@@viewOff:render
  },
});

export default ViewRecipe;
